import React from 'react';

export const Projects = () => (
<div>
<h2>Oregon State Esports </h2>
<p>I am broke college Student LLLLLLLLLLLLLLLLLLLLLLLLLL </p>
<p>LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL</p>
<p>LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL</p>
<p>LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL </p>
<p>LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL </p>
<p>LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL </p>
<p>LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL</p>
<p>WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW </p>
<p>WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW </p>
<p>WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW </p>
<p>WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW</p>

</div>
)
